version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 777422376006.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t python_app:latest .
      - docker tag python_app:latest 777422376006.dkr.ecr.us-east-1.amazonaws.com/python_app:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 777422376006.dkr.ecr.us-east-1.amazonaws.com/python_app:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"python-app","imageUri":"777422376006.dkr.ecr.us-east-1.amazonaws.com/python_app:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"777422376006.dkr.ecr.us-east-1.amazonaws.com/python_app:latest"}' > imageDetail.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json

  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
        - taskdef.json

    ImageArtifact:
      files:
        - imageDetail.json